-- TASK-020: exact project-local Area boundary; no AREA-to-PROJECT fallback.
create table public.project_areas (
 id uuid primary key default gen_random_uuid(), project_id uuid not null references public.projects(id) on delete restrict,
 code text not null check(code ~ '[^[:space:]]'), name text not null check(name ~ '[^[:space:]]'), description text,
 created_at timestamptz not null default now(), created_by uuid not null references auth.users(id) on delete restrict,
 unique(project_id,code), unique(project_id,id)
);
create table public.project_member_areas (
 id uuid primary key default gen_random_uuid(), project_id uuid not null references public.projects(id) on delete restrict,
 project_member_id uuid not null, project_area_id uuid not null, assigned_at timestamptz not null default now(), assigned_by uuid not null references auth.users(id), removed_at timestamptz, removed_by uuid references auth.users(id),
 foreign key(project_id,project_member_id) references public.project_members(project_id,id) on delete restrict, foreign key(project_id,project_area_id) references public.project_areas(project_id,id) on delete restrict, check((removed_at is null)=(removed_by is null))
);
create unique index project_member_areas_active_key on public.project_member_areas(project_member_id,project_area_id) where removed_at is null;
alter table public.works add column project_area_id uuid;
alter table public.works add constraint works_project_area_fkey foreign key(project_id,project_area_id) references public.project_areas(project_id,id) on delete restrict;
alter table public.work_progress_entries add constraint work_progress_entries_project_id_id_key unique(project_id,id);
create table public.work_progress_changes (
 command_id uuid primary key, project_id uuid not null, work_id uuid not null, project_area_id uuid not null, quantity numeric not null check(quantity>0), recorded_for_date date not null, note text, actor_user_id uuid not null references auth.users(id), actor_project_member_id uuid not null, work_progress_entry_id uuid not null, occurred_at timestamptz not null default now(),
 unique(project_id,command_id), foreign key(project_id,work_id) references public.works(project_id,id), foreign key(project_id,project_area_id) references public.project_areas(project_id,id), foreign key(project_id,actor_project_member_id) references public.project_members(project_id,id), foreign key(project_id,work_progress_entry_id) references public.work_progress_entries(project_id,id) deferrable initially deferred
);
alter table public.events add column progress_change_id uuid, add column project_area_id uuid;
alter table public.audit_entries add column progress_change_id uuid, add column project_area_id uuid;
alter table public.events add foreign key(project_id,progress_change_id) references public.work_progress_changes(project_id,command_id);
alter table public.audit_entries add foreign key(project_id,progress_change_id) references public.work_progress_changes(project_id,command_id);
alter table public.events drop constraint events_type_subject_check;
alter table public.events add constraint events_type_subject_check check ((event_type='task.created' and subject_type='task' and lifecycle_transition_id is null and assignment_change_id is null and progress_change_id is null) or (event_type='work.status_changed' and subject_type='work' and lifecycle_transition_id is not null and assignment_change_id is null and progress_change_id is null) or (event_type='work.assignment_changed' and subject_type='work' and lifecycle_transition_id is null and assignment_change_id is not null and progress_change_id is null) or (event_type='work.progress_reported' and subject_type='work' and lifecycle_transition_id is null and assignment_change_id is null and progress_change_id is not null and project_area_id is not null));
alter table public.audit_entries drop constraint audit_entries_action_subject_check;
alter table public.audit_entries drop constraint audit_entries_lifecycle_context_check;
alter table public.audit_entries add constraint audit_entries_action_subject_check check ((action_key in ('document.issue_for_work','document.issue_withdrawn') and subject_type='document_issue_for_work') or (action_key='document_impact.detected' and subject_type='document_impact') or (action_key='task.created' and subject_type='task') or (action_key='notification.read' and subject_type='notification') or (action_key='document_impact.acknowledged' and subject_type='acknowledgement') or (action_key in ('work.ready','work.started','work.blocked','work.unblocked','work.ready_for_inspection','work.rework_required','work.accepted','work.closed') and subject_type='work' and lifecycle_transition_id is not null) or (action_key in ('work.assigned','work.reassigned') and subject_type='work' and assignment_change_id is not null) or (action_key='work.progress_reported' and subject_type='work' and progress_change_id is not null and project_area_id is not null));
alter table public.audit_entries add constraint audit_entries_lifecycle_context_check check ((subject_type='work' and ((lifecycle_transition_id is not null and assignment_change_id is null and progress_change_id is null) or (lifecycle_transition_id is null and assignment_change_id is not null and progress_change_id is null) or (lifecycle_transition_id is null and assignment_change_id is null and progress_change_id is not null)) and actor_user_id is not null and actor_project_member_id is not null) or (subject_type<>'work' and lifecycle_transition_id is null and assignment_change_id is null and progress_change_id is null));
create unique index events_progress_change_key on public.events(progress_change_id) where progress_change_id is not null;
create unique index audit_entries_progress_change_key on public.audit_entries(progress_change_id) where progress_change_id is not null;
alter table public.project_areas enable row level security; alter table public.project_member_areas enable row level security; alter table public.work_progress_changes enable row level security;
revoke all on public.project_areas,public.project_member_areas,public.work_progress_changes from public,anon,authenticated; grant select on public.project_areas,public.project_member_areas to authenticated;
create policy project_areas_select on public.project_areas for select to authenticated using(private.is_active_project_member(project_id));
create policy project_member_areas_own_select on public.project_member_areas for select to authenticated using(exists(select 1 from public.project_members pm where pm.id=project_member_id and pm.project_id=project_member_areas.project_id and pm.user_id=auth.uid() and pm.status='active'));
revoke insert,update,delete on public.work_progress_entries from public,anon,authenticated; drop policy if exists work_progress_entries_insert_project_permission on public.work_progress_entries;
create function public.report_work_progress(p_work_id uuid,p_quantity numeric,p_recorded_for_date date,p_note text,p_command_id uuid) returns uuid language plpgsql security definer set search_path='' as $$
declare actor uuid:=auth.uid(); member_id uuid; w public.works%rowtype; receipt public.work_progress_changes%rowtype; entry_id uuid; report_date date:=coalesce(p_recorded_for_date,current_date); clean_note text:=nullif(btrim(p_note),''); begin
 if actor is null then raise insufficient_privilege using message='work.progress.report permission required'; end if; if p_command_id is null or p_quantity is null or p_quantity<=0 or length(clean_note)>2000 then raise exception 'invalid progress input' using errcode='22023'; end if;
 select * into w from public.works where id=p_work_id for update; if not found then raise no_data_found using message='work not found'; end if; perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended(p_command_id::text,20020)); select * into receipt from public.work_progress_changes where command_id=p_command_id;
 if found then if receipt.work_id is distinct from p_work_id or receipt.quantity is distinct from p_quantity or receipt.recorded_for_date is distinct from report_date or receipt.note is distinct from clean_note or receipt.actor_user_id is distinct from actor then raise exception 'progress command id conflict' using errcode='WP002'; end if; return receipt.work_progress_entry_id; end if;
 select pm.id into member_id from public.project_members pm join public.project_organizations po on po.id=pm.project_organization_id and po.project_id=pm.project_id and po.status='active' where pm.project_id=w.project_id and pm.user_id=actor and pm.status='active';
 if member_id is null or w.project_area_id is null or not private.has_project_permission_grant(w.project_id,'work.progress.report','area') or not exists(select 1 from public.project_member_areas pma where pma.project_id=w.project_id and pma.project_member_id=member_id and pma.project_area_id=w.project_area_id and pma.removed_at is null) then raise insufficient_privilege using message='exact area progress permission required'; end if;
 entry_id:=gen_random_uuid(); insert into public.work_progress_entries(id,project_id,work_id,work_date,quantity,note,created_by) values(entry_id,w.project_id,w.id,report_date,p_quantity,clean_note,actor); insert into public.work_progress_changes(command_id,project_id,work_id,project_area_id,quantity,recorded_for_date,note,actor_user_id,actor_project_member_id,work_progress_entry_id) values(p_command_id,w.project_id,w.id,w.project_area_id,p_quantity,report_date,clean_note,actor,member_id,entry_id);
 insert into public.audit_entries(project_id,action_key,subject_type,subject_id,actor_user_id,actor_project_member_id,progress_change_id,project_area_id) values(w.project_id,'work.progress_reported','work',w.id,actor,member_id,p_command_id,w.project_area_id); insert into public.events(project_id,event_type,subject_type,subject_id,actor_user_id,progress_change_id,project_area_id) values(w.project_id,'work.progress_reported','work',w.id,actor,p_command_id,w.project_area_id); return entry_id; end $$;
revoke all on function public.report_work_progress(uuid,numeric,date,text,uuid) from public,anon,authenticated; grant execute on function public.report_work_progress(uuid,numeric,date,text,uuid) to authenticated;
-- Multiple immutable reports for one Work are allowed; uniqueness is per change receipt.
drop index public.events_legacy_business_event_key;
create unique index events_legacy_business_event_key on public.events(project_id,event_type,subject_type,subject_id) where lifecycle_transition_id is null and assignment_change_id is null and progress_change_id is null;
drop index public.audit_entries_legacy_action_subject_key;
create unique index audit_entries_legacy_action_subject_key on public.audit_entries(project_id,action_key,subject_type,subject_id) where lifecycle_transition_id is null and assignment_change_id is null and progress_change_id is null;

