-- TASK-021: project-scoped Area administration. AREA remains a context only.
insert into public.permissions(key, description) values
  ('project_area.manage', 'Управлять зонами работ проекта'),
  ('project_area.assign_members', 'Назначать участников проекта в зоны работ')
on conflict (key) do nothing;
insert into public.role_permissions(role_id, permission_id, scope_type)
select r.id, p.id, 'project' from public.roles r cross join public.permissions p
where r.code = 'construction_director' and p.key in ('project_area.manage', 'project_area.assign_members')
on conflict (role_id, permission_id) do nothing;
alter table public.project_member_areas add column removal_reason text,
  add constraint project_member_areas_removal_reason_check check ((removed_at is null and removal_reason is null) or (removed_at is not null and removal_reason = btrim(removal_reason) and length(removal_reason) between 1 and 2000)),
  add constraint project_member_areas_project_id_id_key unique(project_id, id);
create table public.project_area_changes (
 command_id uuid primary key, project_id uuid not null references public.projects(id) on delete restrict,
 command_name text not null check (command_name in ('create_project_area','update_project_area','assign_project_member_area','remove_project_member_area')),
 project_area_id uuid not null, project_member_id uuid, project_member_area_id uuid, code text, name text, description text, reason text,
 actor_user_id uuid not null references auth.users(id) on delete restrict, actor_project_member_id uuid not null, changed boolean not null, occurred_at timestamptz not null default now(),
 unique(project_id,command_id), foreign key(project_id,project_area_id) references public.project_areas(project_id,id) deferrable initially deferred,
 foreign key(project_id,project_member_id) references public.project_members(project_id,id) deferrable initially deferred,
 foreign key(project_id,project_member_area_id) references public.project_member_areas(project_id,id) deferrable initially deferred,
 foreign key(project_id,actor_project_member_id) references public.project_members(project_id,id) deferrable initially deferred,
 check(reason is null or (reason=btrim(reason) and length(reason) between 1 and 2000))
);
alter table public.project_area_changes enable row level security; revoke all on public.project_area_changes from public,anon,authenticated;
alter table public.events add column area_change_id uuid, add column project_member_area_id uuid, add column area_reason text;
alter table public.audit_entries add column area_change_id uuid, add column project_member_area_id uuid, add column area_reason text;
alter table public.events add foreign key(project_id,area_change_id) references public.project_area_changes(project_id,command_id), add foreign key(project_id,project_member_area_id) references public.project_member_areas(project_id,id);
alter table public.audit_entries add foreign key(project_id,area_change_id) references public.project_area_changes(project_id,command_id), add foreign key(project_id,project_member_area_id) references public.project_member_areas(project_id,id);alter table public.events drop constraint events_type_subject_check;
alter table public.events add constraint events_type_subject_check check (
 (event_type='task.created' and subject_type='task' and lifecycle_transition_id is null and assignment_change_id is null and progress_change_id is null and area_change_id is null) or
 (event_type='work.status_changed' and subject_type='work' and lifecycle_transition_id is not null and assignment_change_id is null and progress_change_id is null and area_change_id is null) or
 (event_type='work.assignment_changed' and subject_type='work' and lifecycle_transition_id is null and assignment_change_id is not null and progress_change_id is null and area_change_id is null) or
 (event_type='work.progress_reported' and subject_type='work' and lifecycle_transition_id is null and assignment_change_id is null and progress_change_id is not null and area_change_id is null and project_area_id is not null) or
 (event_type in ('project_area.created','project_area.updated') and subject_type='project_area' and area_change_id is not null and project_area_id is not null) or
 (event_type in ('project_area.member_assigned','project_area.member_removed') and subject_type='project_member_area' and area_change_id is not null and project_area_id is not null and project_member_area_id is not null)
);
alter table public.audit_entries drop constraint audit_entries_action_subject_check; alter table public.audit_entries drop constraint audit_entries_lifecycle_context_check;
alter table public.audit_entries add constraint audit_entries_action_subject_check check (
 (action_key in ('document.issue_for_work','document.issue_withdrawn') and subject_type='document_issue_for_work') or (action_key='document_impact.detected' and subject_type='document_impact') or (action_key='task.created' and subject_type='task') or (action_key='notification.read' and subject_type='notification') or (action_key='document_impact.acknowledged' and subject_type='acknowledgement') or
 (action_key in ('work.ready','work.started','work.blocked','work.unblocked','work.ready_for_inspection','work.rework_required','work.accepted','work.closed') and subject_type='work' and lifecycle_transition_id is not null) or (action_key in ('work.assigned','work.reassigned') and subject_type='work' and assignment_change_id is not null) or (action_key='work.progress_reported' and subject_type='work' and progress_change_id is not null and project_area_id is not null) or
 (action_key in ('project_area.created','project_area.updated') and subject_type='project_area' and area_change_id is not null and project_area_id is not null) or (action_key in ('project_area.member_assigned','project_area.member_removed') and subject_type='project_member_area' and area_change_id is not null and project_area_id is not null and project_member_area_id is not null)
);
alter table public.audit_entries add constraint audit_entries_lifecycle_context_check check (
 (subject_type='work' and ((lifecycle_transition_id is not null and assignment_change_id is null and progress_change_id is null and area_change_id is null) or (lifecycle_transition_id is null and assignment_change_id is not null and progress_change_id is null and area_change_id is null) or (lifecycle_transition_id is null and assignment_change_id is null and progress_change_id is not null and area_change_id is null)) and actor_user_id is not null and actor_project_member_id is not null) or
 (subject_type in ('project_area','project_member_area') and area_change_id is not null and actor_user_id is not null and actor_project_member_id is not null) or
 (subject_type not in ('work','project_area','project_member_area') and lifecycle_transition_id is null and assignment_change_id is null and progress_change_id is null and area_change_id is null)
);
create unique index events_area_change_key on public.events(area_change_id) where area_change_id is not null;
create unique index audit_entries_area_change_key on public.audit_entries(area_change_id) where area_change_id is not null;
create policy project_member_areas_management_select on public.project_member_areas for select to authenticated using (private.is_active_project_member(project_id) and (private.has_project_permission_grant(project_id,'project_area.manage','project') or private.has_project_permission_grant(project_id,'project_area.assign_members','project')));
create view public.project_area_member_candidates with (security_barrier=true) as select pm.id,pm.project_id from public.project_members pm join public.project_organizations po on po.id=pm.project_organization_id and po.project_id=pm.project_id and po.status='active' where pm.status='active' and private.is_active_project_member(pm.project_id) and private.has_project_permission_grant(pm.project_id,'project_area.assign_members','project');
revoke all on public.project_area_member_candidates from public,anon,authenticated; grant select on public.project_area_member_candidates to authenticated;
revoke insert,update,delete on public.project_areas,public.project_member_areas from public,anon,authenticated;
create function private.require_project_area_actor(p_project_id uuid,p_permission text) returns uuid language plpgsql security definer set search_path='' as $$ declare actor uuid:=auth.uid(); actor_member uuid; begin if actor is null then raise insufficient_privilege using message='project area permission required'; end if; select pm.id into actor_member from public.project_members pm join public.project_organizations po on po.id=pm.project_organization_id and po.project_id=pm.project_id and po.status='active' where pm.project_id=p_project_id and pm.user_id=actor and pm.status='active' and private.has_project_permission_grant(p_project_id,p_permission,'project') for share of pm,po; if actor_member is null then raise insufficient_privilege using message='exact project area permission required'; end if; return actor_member; end $$;
revoke all on function private.require_project_area_actor(uuid,text) from public,anon,authenticated;
create function public.create_project_area(p_project_id uuid,p_code text,p_name text,p_description text,p_command_id uuid) returns uuid language plpgsql security definer set search_path='' as $$
declare actor uuid:=auth.uid(); member uuid; receipt public.project_area_changes%rowtype; result uuid:=gen_random_uuid(); code_ text:=nullif(btrim(p_code),''); name_ text:=nullif(btrim(p_name),''); description_ text:=nullif(btrim(p_description),''); begin
 if p_command_id is null or code_ is null or name_ is null or length(code_)>200 or length(name_)>500 or length(description_)>2000 then raise exception 'invalid project area input' using errcode='22023'; end if; perform pg_advisory_xact_lock(hashtextextended(p_command_id::text,21021)); select * into receipt from public.project_area_changes where command_id=p_command_id;
 if found then if receipt.command_name<>'create_project_area' or receipt.project_id is distinct from p_project_id or receipt.code is distinct from code_ or receipt.name is distinct from name_ or receipt.description is distinct from description_ or receipt.actor_user_id is distinct from actor then raise exception 'project area command id conflict' using errcode='PA021'; end if; return receipt.project_area_id; end if;
 member:=private.require_project_area_actor(p_project_id,'project_area.manage'); insert into public.project_areas(id,project_id,code,name,description,created_by) values(result,p_project_id,code_,name_,description_,actor); insert into public.project_area_changes(command_id,project_id,command_name,project_area_id,code,name,description,actor_user_id,actor_project_member_id,changed) values(p_command_id,p_project_id,'create_project_area',result,code_,name_,description_,actor,member,true); insert into public.audit_entries(project_id,action_key,subject_type,subject_id,actor_user_id,actor_project_member_id,area_change_id,project_area_id) values(p_project_id,'project_area.created','project_area',result,actor,member,p_command_id,result); insert into public.events(project_id,event_type,subject_type,subject_id,actor_user_id,area_change_id,project_area_id) values(p_project_id,'project_area.created','project_area',result,actor,p_command_id,result); return result; end $$;
create function public.update_project_area(p_project_area_id uuid,p_name text,p_description text,p_command_id uuid) returns uuid language plpgsql security definer set search_path='' as $$
declare actor uuid:=auth.uid(); member uuid; receipt public.project_area_changes%rowtype; area public.project_areas%rowtype; name_ text:=nullif(btrim(p_name),''); description_ text:=nullif(btrim(p_description),''); changed_ boolean; begin
 if p_command_id is null or name_ is null or length(name_)>500 or length(description_)>2000 then raise exception 'invalid project area input' using errcode='22023'; end if; perform pg_advisory_xact_lock(hashtextextended(p_command_id::text,21021)); select * into receipt from public.project_area_changes where command_id=p_command_id; if found then if receipt.command_name<>'update_project_area' or receipt.project_area_id is distinct from p_project_area_id or receipt.name is distinct from name_ or receipt.description is distinct from description_ or receipt.actor_user_id is distinct from actor then raise exception 'project area command id conflict' using errcode='PA021'; end if; return receipt.project_area_id; end if;
 select * into area from public.project_areas where id=p_project_area_id for update; if not found then raise no_data_found using message='project area not found'; end if; member:=private.require_project_area_actor(area.project_id,'project_area.manage'); changed_:=area.name is distinct from name_ or area.description is distinct from description_; if changed_ then update public.project_areas set name=name_,description=description_ where id=area.id; end if; insert into public.project_area_changes(command_id,project_id,command_name,project_area_id,name,description,actor_user_id,actor_project_member_id,changed) values(p_command_id,area.project_id,'update_project_area',area.id,name_,description_,actor,member,changed_); if changed_ then insert into public.audit_entries(project_id,action_key,subject_type,subject_id,actor_user_id,actor_project_member_id,area_change_id,project_area_id) values(area.project_id,'project_area.updated','project_area',area.id,actor,member,p_command_id,area.id); insert into public.events(project_id,event_type,subject_type,subject_id,actor_user_id,area_change_id,project_area_id) values(area.project_id,'project_area.updated','project_area',area.id,actor,p_command_id,area.id); end if; return area.id; end $$;
create function public.assign_project_member_area(p_project_area_id uuid,p_project_member_id uuid,p_command_id uuid,p_reason text default null) returns uuid language plpgsql security definer set search_path='' as $$
declare actor uuid:=auth.uid(); member uuid; receipt public.project_area_changes%rowtype; area public.project_areas%rowtype; target public.project_members%rowtype; relation public.project_member_areas%rowtype; result uuid; reason_ text:=nullif(btrim(p_reason),''); changed_ boolean:=false; begin
 if p_command_id is null or p_project_member_id is null or length(reason_)>2000 then raise exception 'invalid project area assignment input' using errcode='22023'; end if; perform pg_advisory_xact_lock(hashtextextended(p_command_id::text,21021)); select * into receipt from public.project_area_changes where command_id=p_command_id; if found then if receipt.command_name<>'assign_project_member_area' or receipt.project_area_id is distinct from p_project_area_id or receipt.project_member_id is distinct from p_project_member_id or receipt.reason is distinct from reason_ or receipt.actor_user_id is distinct from actor then raise exception 'project area command id conflict' using errcode='PA021'; end if; return receipt.project_member_area_id; end if;
 select * into area from public.project_areas where id=p_project_area_id for update; if not found then raise no_data_found using message='project area not found'; end if; member:=private.require_project_area_actor(area.project_id,'project_area.assign_members'); select pm.* into target from public.project_members pm join public.project_organizations po on po.id=pm.project_organization_id and po.project_id=pm.project_id and po.status='active' where pm.id=p_project_member_id and pm.project_id=area.project_id and pm.status='active' for update of pm,po; if not found then raise insufficient_privilege using message='active same-project member required'; end if;
 select * into relation from public.project_member_areas where project_id=area.project_id and project_member_id=target.id and project_area_id=area.id and removed_at is null for update; if found then result:=relation.id; else result:=gen_random_uuid(); changed_:=true; insert into public.project_member_areas(id,project_id,project_member_id,project_area_id,assigned_by) values(result,area.project_id,target.id,area.id,actor); end if;
 insert into public.project_area_changes(command_id,project_id,command_name,project_area_id,project_member_id,project_member_area_id,reason,actor_user_id,actor_project_member_id,changed) values(p_command_id,area.project_id,'assign_project_member_area',area.id,target.id,result,reason_,actor,member,changed_); if changed_ then insert into public.audit_entries(project_id,action_key,subject_type,subject_id,actor_user_id,actor_project_member_id,area_change_id,project_area_id,project_member_area_id,to_project_member_id,area_reason) values(area.project_id,'project_area.member_assigned','project_member_area',result,actor,member,p_command_id,area.id,result,target.id,reason_); insert into public.events(project_id,event_type,subject_type,subject_id,actor_user_id,area_change_id,project_area_id,project_member_area_id,to_project_member_id,area_reason) values(area.project_id,'project_area.member_assigned','project_member_area',result,actor,p_command_id,area.id,result,target.id,reason_); end if; return result; end $$;
create function public.remove_project_member_area(p_project_member_area_id uuid,p_command_id uuid,p_reason text) returns uuid language plpgsql security definer set search_path='' as $$
declare actor uuid:=auth.uid(); member uuid; receipt public.project_area_changes%rowtype; relation public.project_member_areas%rowtype; area public.project_areas%rowtype; target public.project_members%rowtype; reason_ text:=nullif(btrim(p_reason),''); changed_ boolean:=false; begin
 if p_command_id is null or reason_ is null or length(reason_)>2000 then raise exception 'invalid project area removal input' using errcode='22023'; end if; perform pg_advisory_xact_lock(hashtextextended(p_command_id::text,21021)); select * into receipt from public.project_area_changes where command_id=p_command_id; if found then if receipt.command_name<>'remove_project_member_area' or receipt.project_member_area_id is distinct from p_project_member_area_id or receipt.reason is distinct from reason_ or receipt.actor_user_id is distinct from actor then raise exception 'project area command id conflict' using errcode='PA021'; end if; return receipt.project_member_area_id; end if;
 select * into relation from public.project_member_areas where id=p_project_member_area_id; if not found then raise no_data_found using message='project member area not found'; end if; select * into area from public.project_areas where id=relation.project_area_id and project_id=relation.project_id for update; member:=private.require_project_area_actor(area.project_id,'project_area.assign_members'); select * into target from public.project_members where id=relation.project_member_id and project_id=area.project_id for update; select * into relation from public.project_member_areas where id=p_project_member_area_id for update; if relation.removed_at is null then changed_:=true; update public.project_member_areas set removed_at=now(),removed_by=actor,removal_reason=reason_ where id=relation.id; end if;
 insert into public.project_area_changes(command_id,project_id,command_name,project_area_id,project_member_id,project_member_area_id,reason,actor_user_id,actor_project_member_id,changed) values(p_command_id,area.project_id,'remove_project_member_area',area.id,target.id,relation.id,reason_,actor,member,changed_); if changed_ then insert into public.audit_entries(project_id,action_key,subject_type,subject_id,actor_user_id,actor_project_member_id,area_change_id,project_area_id,project_member_area_id,from_project_member_id,area_reason) values(area.project_id,'project_area.member_removed','project_member_area',relation.id,actor,member,p_command_id,area.id,relation.id,target.id,reason_); insert into public.events(project_id,event_type,subject_type,subject_id,actor_user_id,area_change_id,project_area_id,project_member_area_id,from_project_member_id,area_reason) values(area.project_id,'project_area.member_removed','project_member_area',relation.id,actor,p_command_id,area.id,relation.id,target.id,reason_); end if; return relation.id; end $$;
revoke all on function public.create_project_area(uuid,text,text,text,uuid),public.update_project_area(uuid,text,text,uuid),public.assign_project_member_area(uuid,uuid,uuid,text),public.remove_project_member_area(uuid,uuid,text) from public,anon,authenticated;
grant execute on function public.create_project_area(uuid,text,text,text,uuid),public.update_project_area(uuid,text,text,uuid),public.assign_project_member_area(uuid,uuid,uuid,text),public.remove_project_member_area(uuid,uuid,text) to authenticated;
